using Helix.Data.Entities;
using Helix.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace Helix.Infrastructure.Seeding
{
    public static class AllergenSeeder
    {
        public static async Task SeedAsync(ApplicationDbContext context)
        {
            // Only seed if the table is completely empty
            if (!await context.Set<AllergenCatalog>().AnyAsync())
            {
                Console.WriteLine("Seeding SNOMED allergy dataset from local CSV file...");
                var allergens = new List<AllergenCatalog>();

                try
                {
                    // Looks for the file generated by the Python script in the root directory
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "snomed_allergies_dataset.csv");

                    if (File.Exists(filePath))
                    {
                        var lines = await File.ReadAllLinesAsync(filePath);

                        // Skip the 1st line (Header: Code, DisplayName, CodeSystem)
                        for (int i = 1; i < lines.Length; i++)
                        {
                            // Split by comma
                            var columns = lines[i].Split(',');

                            // Ensure we have at least the Code and DisplayName columns
                            if (columns.Length >= 2)
                            {
                                allergens.Add(new AllergenCatalog
                                {
                                    Code = columns[0].Trim(),
                                    DisplayName = columns[1].Trim(),
                                    CodeSystem = "SNOMED"
                                });
                            }
                        }

                        // Entity Framework handles this safely without needing BULK INSERT permissions!
                        await context.Set<AllergenCatalog>().AddRangeAsync(allergens);
                        await context.SaveChangesAsync();

                        Console.WriteLine($"Successfully seeded {allergens.Count} medical substances into the database!");
                    }
                    else
                    {
                        Console.WriteLine("WARNING: Could not find snomed_allergies_dataset.csv in the project root.");
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to seed allergies: {ex.Message}");
                }
            }
        }
    }
}