using Helix.Data.Entities;
using Helix.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;

namespace Helix.Infrastructure.Seeding
{
    public static class ChronicDiseaseSeeder
    {
        public static async Task SeedAsync(ApplicationDbContext context)
        {
            // Only seed if the lookup table is completely empty
            if (!await context.Set<ChronicDiseaseCatalog>().AnyAsync())
            {
                Console.WriteLine("Seeding SNOMED chronic disease dataset from local CSV file...");
                var diseases = new List<ChronicDiseaseCatalog>();

                try
                {
                    // Looks for the file generated by the Python script in the root directory
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "snomed_chronic_diseases_dataset.csv");

                    if (File.Exists(filePath))
                    {
                        var lines = await File.ReadAllLinesAsync(filePath);

                        // Skip the 1st line (Header: Code, DisplayName, CodeSystem)
                        for (int i = 1; i < lines.Length; i++)
                        {
                            // Split by comma. 
                            // Note: If display names contain commas, a more robust CSV parser (like CsvHelper) is recommended.
                            var columns = lines[i].Split(',');

                            // Ensure we have at least the Code and DisplayName columns
                            if (columns.Length >= 2)
                            {
                                diseases.Add(new ChronicDiseaseCatalog
                                {
                                    Code = columns[0].Trim(),
                                    DisplayName = columns[1].Trim(),
                                    CodeSystem = "SNOMED"
                                });
                            }
                        }

                        // Entity Framework safely handles massive inserts
                        await context.Set<ChronicDiseaseCatalog>().AddRangeAsync(diseases);
                        await context.SaveChangesAsync();

                        Console.WriteLine($"Successfully seeded {diseases.Count} chronic diseases into the database!");
                    }
                    else
                    {
                        Console.WriteLine("WARNING: Could not find snomed_chronic_diseases_dataset.csv in the project root.");
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to seed chronic diseases: {ex.Message}");
                }
            }
        }
    }
}