using Helix.Data.Entities;
using Helix.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;

namespace Helix.Infrastructure.Seeding
{
    public static class SpecialtySeeder
    {
        public static async Task SeedAsync(ApplicationDbContext context)
        {
            // Only run the seeder if the SpecialtyCatalog table is completely empty
            if (!await context.Set<SpecialtyCatalog>().AnyAsync())
            {
                Console.WriteLine("Seeding SNOMED clinical specialties dataset from local CSV file...");
                var specialties = new List<SpecialtyCatalog>();

                try
                {
                    // Looks for the file generated by the Python script in the project root directory
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "snomed_specialties_dataset.csv");

                    if (File.Exists(filePath))
                    {
                        var lines = await File.ReadAllLinesAsync(filePath);

                        // Skip the 1st line (Header: Code, DisplayName, CodeSystem)
                        for (int i = 1; i < lines.Length; i++)
                        {
                            var columns = lines[i].Split(',');

                            // Ensure we have at least the Code and DisplayName columns
                            if (columns.Length >= 2)
                            {
                                specialties.Add(new SpecialtyCatalog
                                {
                                    Code = columns[0].Trim(),
                                    DisplayName = columns[1].Trim(),
                                    CodeSystem = "SNOMED"
                                });
                            }
                        }

                        // Entity Framework safely handles the bulk insert
                        await context.Set<SpecialtyCatalog>().AddRangeAsync(specialties);
                        await context.SaveChangesAsync();

                        Console.WriteLine($"Successfully seeded {specialties.Count} medical specialties into the database!");
                    }
                    else
                    {
                        Console.WriteLine("WARNING: Could not find snomed_specialties_dataset.csv in the project root.");
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to seed specialties: {ex.Message}");
                }
            }
        }
    }
}